version: '3'

services:
  # app:
  #   image: rafante/sats_game_app_core
  #   container_name: core_app
  #   ports:
  #     - "3000:3000"
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30 #check for updates once per day
    restart: unless-stopped
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    volumes:
      - ./.data:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root